name: PwshCoreAzCli-v0.$(date:yyMMdd)$(rev:.r)

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: VersionExtractor@5
  name: build
  displayName: 'Version extractor digit'
  inputs:
    stringToAnalyze: '$(Build.BuildNumber)'

- task: Docker@2
  displayName: 'Build and Push to ExpertaMain Registry'
  inputs:
    containerRegistry: 'ExpertaMainRegistry'
    repository: '$(Build.SourceBranchName).PwshCoreAzCli'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: '$(build.fullVersion)'

- task: Docker@2
  displayName: 'Build and Push lturmel docker hub'
  inputs:
    containerRegistry: 'docker-lturmel'
    repository: '$(Build.SourceBranchName).PwshCoreAzCli'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: '$(build.fullVersion)'
